cuda_device: 0
step: 100
epoch: 1000
lr: 0.01
lr_mixup: 0.02
hid_num: 16
dropout_rate1_before: 0.6
dropout_rate2_before: 0.6
dropout_rate1_high: 0.1
dropout_rate1_mixup: 0.6
dropout_rate2_mixup: 0.6
weight_decay: 0.0005
weight_decay_mixup: 0.0003
with_test_data: "yes"
score_threshold_mixup: 0.8
score_threshold_high: 0.5
patient: 1000
alpha: 0.4
nb_heads: 8
nb_heads2: 1
