cuda_device: 0
step: 100
epoch: 1000
lr: 0.01
lr_mixup: 0.03
hid_num: 16
dropout_rate1_before: 0.5
dropout_rate2_before: 0.5
dropout_rate1_high: 0.8
dropout_rate1_mixup: 0.9
dropout_rate2_mixup: 0.5
weight_decay: 0.0005
weight_decay_mixup: 0.000001
with_test_data: "yes"
score_threshold_mixup: 0.9
score_threshold_high: 0.0
patient: 1000
alpha: 0.2
nb_heads: 8
nb_heads2: 1
vote_num: 3