cuda_device: 0
step: 100
epoch: 1000
lr: 0.01
lr_mixup: 0.015
hid_num: 128
dropout_rate1_before: 0.9
dropout_rate2_before: 0.005
dropout_rate1_high: 0.7
dropout_rate1_mixup: 0.8
dropout_rate2_mixup: 0.005
weight_decay: 0.0005
weight_decay_mixup: 0.0001
with_test_data: "yes"
score_threshold_mixup: 0.8
score_threshold_high: 0.5
vote_num: 5
patient: 1000
