cuda_device: 0
step: 100
epoch: 1000
lr: 0.01
lr_mixup: 0.015
hid_num: 256
dropout_rate1_before: 0.0
dropout_rate2_before: 0.5
dropout_rate1_high: 0.3
dropout_rate1_mixup: 0.0
dropout_rate2_mixup: 0.5
weight_decay: 0.00001
weight_decay_mixup: 0.000000
with_test_data: "yes"
score_threshold_mixup: 0.5
score_threshold_high: 0.1
patient: 1000
layer: 3
vote_num: 3