cuda_device: 0
step: 100
epoch: 1000
lr: 0.005
lr_mixup: 0.01
hid_num: 256
dropout_rate1_before: 0.3
dropout_rate2_before: 0.1
dropout_rate1_high: 0.4
dropout_rate1_mixup: 0.3
dropout_rate2_mixup: 0.1
weight_decay: 0.0001
weight_decay_mixup: 0.00005
with_test_data: "yes"
score_threshold_mixup: 0.5
score_threshold_high: 0.1
patience: 1000
layer: 3